// zotero-bridge/src/bibtex.ts — Convert Zotero items to BibTeX format
const ITEM_TYPE_MAP = {
    journalArticle: 'article',
    book: 'book',
    bookSection: 'incollection',
    conferencePaper: 'inproceedings',
    thesis: 'mastersthesis',
    report: 'techreport',
    webpage: 'misc',
    patent: 'misc',
    presentation: 'misc',
    letter: 'misc',
    manuscript: 'unpublished',
};
function sanitizeBibtexKey(key) {
    return key.replace(/[^a-zA-Z0-9_:-]/g, '_');
}
function escapeBibtex(value) {
    return value.replace(/([&%$#_{}~^\\])/g, '\\$1');
}
/**
 * Convert a single Zotero item to a BibTeX entry string.
 */
export function zoteroItemToBibtex(item) {
    const entryType = ITEM_TYPE_MAP[item.itemType] ?? 'misc';
    const key = sanitizeBibtexKey(item.key);
    const fields = [];
    if (item.title) {
        fields.push(`  title = {${escapeBibtex(item.title)}}`);
    }
    if (item.creators.length > 0) {
        const authorStr = item.creators.map(escapeBibtex).join(' and ');
        fields.push(`  author = {${authorStr}}`);
    }
    if (item.date) {
        // Extract year from various date formats
        const yearMatch = item.date.match(/(\d{4})/);
        if (yearMatch) {
            fields.push(`  year = {${yearMatch[1]}}`);
        }
    }
    return `@${entryType}{${key},\n${fields.join(',\n')}\n}`;
}
/**
 * Convert a collection of Zotero items to a complete .bib file content string.
 */
export function exportCollectionToBibtex(items) {
    const header = `% BibTeX file generated by Thesis Research OS\n% Source: Zotero connector (${items.length} items)\n% Generated: ${new Date().toISOString()}\n\n`;
    const entries = items.map(zoteroItemToBibtex).join('\n\n');
    return header + entries + '\n';
}
